name: shared_preferences_cache
description: A Cache for Flutter based on Shared Preferences to cache results of heavy calcuations
  or API calls.
version: 0.1.0+3
homepage: https://github.com/darnreich/flutter_shared_preferences_cache

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  shared_preferences_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
